<a href="https://colab.research.google.com/github/lyntos/Learning/blob/main/3_cond_loop_join.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conditional Statement:
A conditional statement in Python is a way to make decisions in your code. It lets your program run different blocks of code depending on whether a condition is True or False.

Basic Idea

Python checks a condition, and:

If it’s True → it runs one block of code

If it’s False → it can run another block (optional)

# Main Types of Conditional Statements

In [ ]:
# 1. Indentation matters (very important)

# Python uses indentation (spaces) to define blocks of code.

x = 10

if x > 5:
    print("Greater than 5")  # must be indented

Greater than 5

Comparison Operators Used

    == (equal to)

    != (not equal)

    > (greater than)

    < (less than)

    >= (greater than or equal)

    <= (less than or equal)

In [ ]:

# 1. if statement

# Executes code only if a condition is true:

age = 18

if age >= 18:
    print("You are an adult")

You are an adult

In [ ]:

# 2. if-else statement

# Provides an alternative if the condition is false:

age = 16

if age >= 18:
    print("Adult")
else:
    print("Minor")

In [ ]:
# 3. if-elif-else statement

# Checks multiple conditions:

score = 85

if score >= 90:
    print("Grade A")
elif score >= 80:
    print("Grade B")
else:
    print("Grade C")

In [ ]:
# 🔹 Logical Operators

# You can combine conditions:

age = 20
has_id = True

if age >= 18 and has_id:
    print("Allowed entry")

Allowed entry

In [ ]:
# Nested conditionals

# You can put an if inside another if.

age = 20
has_id = True

if age >= 18:
    if has_id:
        print("You can enter")

In [ ]:
# Short-hand (ternary) conditional

# A one-line version of if-else:

age = 18
status = "Adult" if age >= 18 else "Minor"
print(status)

In [ ]:
# Truthy and Falsy values

# In Python, some values are automatically considered False:

# 0
# None
# "" (empty string)
# [], {} (empty collections)

# Everything else is usually True.

name = ""

if name:
    print("Name exists")
else:
    print("Name is empty")

Name is empty

In [ ]:
# Combining multiple conditions

# Using and, or, and not:

x = 5

if x > 0 and x < 10:
    print("Between 1 and 9")

Between 1 and 9

In [ ]:
# Membership conditions

# Check if something is in a list/string:

fruits = ["apple", "banana"]

if "apple" in fruits:
    print("Apple is there")

Apple is there

In [ ]:
# Pass statement

# Sometimes you need an empty block:

if True:
    pass  # placeholder, does nothing

In [ ]:
# Example 1: if with pass
x = 10

if x > 5:
    pass  # do nothing for now
else:
    print("x is 5 or less")

print("Program continues...")
# The if block is executed but does nothing because of pass.

Program continues...

In [ ]:
# Example 2: Using pass as a placeholder for future code
age = 15

if age < 18:
    pass  # will add code later for minors
else:
    print("Adult")

print("Check completed")
# You can write the if structure first and fill in logic later.

Check completed

In [ ]:
# Match-case (Python 3.10+)
# What is match-case?

# match-case is a new control flow statement in Python 3.10+ that works like a switch-case in other languages.
# It is used to compare a value against multiple cases and execute the matching block.

# Makes code cleaner and easier to read than many if-elif-else statements.

# A cleaner alternative to multiple elif:

day = "Tuesday"

match day:
    case "Monday":
        print("Start of week")
    case "Friday":
        print("Almost weekend")
    case _:
        print("Regular day")

Regular day

# Avoid common mistakes

Using = instead of ==

Forgetting indentation

Writing overly complex conditions

# Looping Statement:

A looping statement (or loop) in Python is used to repeat a block of code multiple times until a condition is met or for a fixed number of times.

You can say:

“A for loop is like telling a robot:
‘Do this task again and again for each item in a group.’”

🔹 Simple definition

“A looping statement is a way to run the same code again and again without writing it multiple times.”

🔹 Why we use loops

    To save time
    To avoid repeating code
    To automate repetitive tasks

🔹 Types of loops in Python
1. for loop

Used when you know how many times to repeat:

2. while loop

Used when you repeat until a condition becomes false:

In [ ]:
# Basic syntax
for item in sequence:
    # code to run

In [ ]:
# Example 1: Printing numbers
for i in range(5):
    print(i)


# range(5) means numbers from 0 to 4
# The loop runs 5 times
# Each time, i gets a new value

0
1
2
3
4

In [ ]:
# Names in a list
students = ["Ali", "Sara", "John"]

for name in students:
    print("Hello", name)

In [ ]:
# Counting candies
for candy in range(1, 6):
    print("You got candy number", candy)

You got candy number 1
You got candy number 2
You got candy number 3
You got candy number 4
You got candy number 5

In [ ]:
# range(start, stop, step)

# Controls how much the number increases each time.

for i in range(1, 10, 2):
    print(i)


    # “Start at 1, jump by 2 each time”

In [ ]:
# Reverse loop (very useful)
for i in range(5, 0, -1):
    print(i)

# Key points for students

range() does not include the stop number

Default start is 0

Default step is 1

Step can be negative (to go backwards)

Question


1)Task for students:
“Print numbers from 1 to 10”

for i in range(1, 10):
    print(i)



2)Can you print even numbers from 1 to 10?

for i in range(2, 11, 2):
    print(i)

In [ ]:
# Multiplication table
for i in range(1, 6):
    print("2 x", i, "=", 2 * i)

# 🧠 Task:
# “Make table of 5”

In [ ]:
# Add numbers (Simple math)
total = 0

for i in range(1, 6):
    total += i

print("Total:", total)

In [ ]:
# Print a pattern ⭐
for i in range(1, 6):
    print("*" * i)

In [ ]:
# Loop through a word
word = "PYTHON"

for letter in word:
    print(letter)

In [ ]:
# Guess the output (interactive game)
for i in range(3):
    print(i * 2)

0
2
4

# While Loop

A while loop in Python is used to repeat a block of code as long as a condition
 is True.

🔹 Simple definition

“A while loop keeps running again and again until the condition becomes false.”

🔹 Basic syntax

while condition:

 code to repeat

In [ ]:
# Example 1: Basic counting
x = 1

while x <= 5:
    print(x)
    x += 1

1
2
3
4
5

In [ ]:
# Example 2: Countdown
x = 5

while x > 0:
    print(x)
    x -= 1

# 👉 Output:

# 5 4 3 2 1

In [ ]:
# Example 3: Infinite loop (important concept)
while True:
    print("This runs forever")

# ⚠️ Runs forever unless stopped manually.

In [ ]:
# Example 4: Using break

# Stops the loop early:

x = 1

while x <= 10:
    if x == 5:
        break
    print(x)
    x += 1

# 👉 Output:

# 1 2 3 4

In [ ]:
# Example 5: Using continue

# Skips one step:

x = 0

while x < 5:
    x += 1
    if x == 3:
        continue
    print(x)

# 👉 Output:

# 1 2 4 5

In [ ]:
# Example 6: User input loop
password = ""

while password != "1234":#“Keep running the loop as long as the password is NOT '1234'”
    password = input("Enter password: ")

print("Access granted")

Enter password: 253
Enter password: 2536
Enter password: 123
Enter password: 1234
Access granted

explanation for password

Why is "1234" written as a string?

Because of this line:

password = input("Enter password: ")

👉 The input() function always returns data as a string (text).

🔹 What that means

If a user types:

1234

Python actually stores it as:

"1234"

(not as the number 1234)

🔹 So we must compare with a string
while password != "1234":

✔ This works because:

"1234" (input) == "1234" (comparison)


🔹 What if we didn’t use a string?

while password != 1234:

❌ This would NOT work properly because:

"1234" (string) ≠ 1234 (integer)

Even though they look the same, Python treats them as different types.

🔹 Simple way

“Whatever the user types is treated as text, so we must compare it with text.”

🔹 Extra (optional concept)

If you want to treat it as a number, you can convert it:

password = int(input("Enter password: "))

Then compare like this:

while password != 1234:

In [ ]:
password = ""

while password != 1234:
    password = int(input("Enter password: "))

print("Access granted")

Enter password: 1234
Access granted

In [ ]:
# using while and if statement to check password
password = ""
while password != "python123":
    password = input("Enter password: ")
    if password != "python123":
        print("Incorrect! Hint: It starts with 'python'")

print("Access granted")

Enter password: hjkhl123
Incorrect! Hint: It starts with 'python'
Enter password: python123
Access granted

In [ ]:
# Example 7: Sum of numbers
total = 0
x = 1

while x <= 5:
    total += x
    x += 1

print("Total:", total)

In [ ]:
# Example 8: While with list
numbers = [10, 20, 30]
i = 0

while i < len(numbers):
    print(numbers[i])
    i += 1

10
20
30

In [ ]:
# Example 9: Nested while loop
i = 1

while i <= 3:
    j = 1
    while j <= 2:
        print(i, j)
        j += 1
    i += 1

1 1
1 2
2 1
2 2
3 1
3 2

# Key points :

Runs while condition is True

Can become infinite if condition never changes

Use break to stop

Use continue to skip

# Simple difference

for loop → when you know how many times

while loop → when you don’t know how many times

# Functions

What is a function in Python?

“A function is a named block of code that does a specific task.

You can use it whenever you want without rewriting the code.”

Think of it like a machine:

You give it inputs → it does something → gives output (optional)

🔹 Why use functions?

Avoid repeating code

Make programs organized

Easier to read and debug

🔹 Basic syntax

def function_name():

    # code block
    print("Hello, World!")

def → keyword to define a function

function_name → the name you give it

Code inside the function is indented

## Step 4: Key points

# Define the function first (def categorize_age(age): ...)

# Call the function with a number (like categorize_age(30))

# Store the result in a variable if you want to use it later (result = categorize_age(30))

# Print the result to see it on the screen

In [ ]:
# Example 1: Simple function
def greet():
    print("Hello, welcome to Python!")

# Call the function:

greet()

# Output:

# Hello, welcome to Python!


# We defined greet() once
# We can use it anytime by calling greet()

In [ ]:
# Function with input (parameters)
def greet_student(name):
    print("Hello,", name)

# Call the function:

greet_student("Ali")
greet_student("Sara")

# Output:

# Hello, Ali
# Hello, Sara

# Explain:

# name is an input for the function
# Each time we call it with a different name, it works automatically

In [ ]:
# Example 3: Function with return value
def add(a, b):
    return a + b

# Call the function:

result = add(5, 3)
print(result)

Output:

8

# Explain:

# add() calculates the sum
# return sends the result back to use later

# example: a mini calculator using functions

In [ ]:
# Step 1: Define functions for operations
# Addition
def add(a, b):
    return a + b

# Subtraction
def subtract(a, b):
    return a - b

# Multiplication
def multiply(a, b):
    return a * b

# Division
def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Cannot divide by zero"

In [ ]:
# Step 2: Use the functions
print("Addition:", add(5, 3))
print("Subtraction:", subtract(10, 4))
print("Multiplication:", multiply(6, 7))
print("Division:", divide(20, 4))
print("Division by zero test:", divide(5, 0))

In [ ]:
# Step 3: Explaination
# Each operation is a function → we defined it once
# We can use it many times → just call the function
# return gives back a value → we can print it or store it in a variable
# Optional check → divide function checks for division by zero

In [ ]:
def	categorize_age(age):
  if	age	<	18:
    return	"Minor"
  elif	age	<	65:
    return	"Adult"
  else:
    return	"Senior"

In [ ]:
result = categorize_age(15)
print(result)

Minor

In [ ]:
print(categorize_age(30))
print(categorize_age(70))

Adult
Senior

In [ ]:
# Step 3: Ask user for input (optional)
age = int(input("Enter your age: "))
category = categorize_age(age)
print("You are a", category)

Enter your age: 18
You are a Adult

In [ ]:
# You	can	then	use	this	function	to	categorize	individuals	in	a	data	frame:
import	pandas	as	pd
#	Sample	data
data	=	pd.DataFrame({'Name':	['Alice',	'Bob',	'Charlie'],
'Age':	[25,	15,	70]})
#	Apply	the	function	to	categorize	age
data['Age	Group']	=	data['Age'].apply(categorize_age)
print(data)

      Name  Age Age\tGroup
0    Alice   25      Adult
1      Bob   15      Minor
2  Charlie   70     Senior

In [ ]:
# To check frequency count--> to	get	a	count	based	on	column	values
# -->Import	states.csv	then use	info	to	get	information	about	the	new	data

In [ ]:
data=	pd.read_csv('/content/states.csv')
data

   first_name  gender     location
0       Wiley    Male      Alberta
1    Kahaleel    Male      Alberta
2         Lee  Female  Connecticut
3      Prisca  Female       Bremen
4   Beniamino  Female  Connecticut
5     Charita    Male      Alberta
6      Ingrid  Female      Alberta
7        Judi  Female  Connecticut
8    Lynnelle  Female      Alberta
9     Willard  Female  Connecticut
10    Kennedy    Male  Connecticut
11        Web    Male      Alberta
12    Tristam    Male  Connecticut
13    Glendon    Male  Connecticut
14     Moreen  Female      Alberta
15     Sheila  Female      Alberta
16     Cyndie  Female      Alberta
17   Clerissa  Female      Alberta
18       Jojo  Female       Bremen
19     Gustaf  Female       Bremen

In [ ]:
print(data.info())

In [ ]:
# Using	the	information	from	the	.info	command	we	can
# check	all	the	possible	values	in	the	location	column	and	their	count,	using
# the	value_counts	function

In [ ]:
print(data.value_counts(["location"]))

location
Alberta        10
Connecticut     7
Bremen          3
Name: count, dtype: int64

In [ ]:
# The	value_counts	is	very	efficient	because	it	enables	the	user	to	get	the
# count	of	multiple	columns	at	the	same	time.	Remember	our	CSV	had
# multiple	columns	so	we	can	add	an	extra	argument.

In [ ]:
print(data.value_counts(["location","gender"]))

location     gender
Alberta      Female    6
             Male      4
Connecticut  Female    4
Bremen       Female    3
Connecticut  Male      3
Name: count, dtype: int64

In [ ]:
# Example:	Comparing	Gender	Distribution	in	Different
# Locations
# Let’s	use	our	states.csv	dataset	to	compare	the	gender	distribution	in
# different	locations.	We’ll	use	the	value_counts	function	to	count	the
# frequency	of	each	gender	in	each	location,	and	then	use	conditional
# statements	to	analyze	the	differences.

In [ ]:
#	Count	the	frequency	of	each	gender	in	each	location
gender_distribution	=	data.value_counts(['location',	'gender'])
print("Gender	distribution	by	location:")
print(gender_distribution)

Gender	distribution	by	location:
location     gender
Alberta      Female    6
             Male      4
Connecticut  Female    4
Bremen       Female    3
Connecticut  Male      3
Name: count, dtype: int64

In [ ]:
# Convert to DataFrame and add column name(OPTIONAL)
gender_distribution = data.value_counts(['location', 'gender']).reset_index()
gender_distribution.columns = ['Location', 'Gender', 'Count']

print("Gender distribution by location:")
print(gender_distribution)
# Step 2: Explanation
# reset_index() → converts the Series into a DataFrame and moves the MultiIndex (location and gender) into columns
# columns = ['Location', 'Gender', 'Count'] → renames all columns
# First column → Location
# Second column → Gender
# Third column → Count (the frequency)

Gender distribution by location:
      Location  Gender  Count
0      Alberta  Female      6
1      Alberta    Male      4
2  Connecticut  Female      4
3       Bremen  Female      3
4  Connecticut    Male      3

# Using	Conditionals	to	Analyze	Differences

Now,	let’s	use	conditional	statements	to	compare	the	gender
distribution	in

two	specific	locations,	for	example,	‘Alberta’	and	‘Connecticut’

In [ ]:


#	Count	the	frequency	of	each	gender	in	each	location
gender_distribution	=	data.value_counts(['location',	'gender'])
print("Gender	distribution	by	location:")
print(gender_distribution)

Gender	distribution	by	location:
location     gender
Alberta      Female    6
             Male      4
Connecticut  Female    4
Bremen       Female    3
Connecticut  Male      3
Name: count, dtype: int64

In [ ]:
#	Compare	gender	distribution	in	Alberta	and	Connecticut
Alberta_distribution	=	gender_distribution['Alberta']
Connecticut_distribution	=	gender_distribution['Connecticut']
if	Alberta_distribution['Male']	>	Connecticut_distribution['Male']:
  print("Alberta	has	more	males	than	Connecticut.")
else:
  print("Connecticut	has	more	males	than	Alberta.")
if	Alberta_distribution['Female']	>	Connecticut_distribution['Female']:
  print("Alberta	has	more	females	than	Connecticut.")
else:
  print("Connecticut	has	more	females	than	Alberta.")

Alberta	has	more	males	than	Connecticut.
Alberta	has	more	females	than	Connecticut.

Handling	Incomplete	Data	Sets

A	value	can	be	missing	in	one	of	two	possible	ways:

Explicitly,	i.e.,	flagged	with	NA.

Implicitly,	i.e.,	simply	not	present	in	the	data

In [ ]:
stocks	=	[[2015,	1,	1.88],	[2015,	2,	0.59],	[2015,	3,	0.35],
[2015,	4],[2016],	[2016,	2,	0.92],	[2016,	3,	0.17],	[2016,	4,
2.66]]
df2	=	pd.DataFrame(stocks,	columns=['year',	'qtr',	'return'])
print(df2)

   year  qtr  return
0  2015  1.0    1.88
1  2015  2.0    0.59
2  2015  3.0    0.35
3  2015  4.0     NaN
4  2016  NaN     NaN
5  2016  2.0    0.92
6  2016  3.0    0.17
7  2016  4.0    2.66

Note:

NaN	(Not	a	Number)	is	a	standard	missing	value	marker	used	in	pandas
for	float	data	types.

None	is	the	Python	singleton	object	that	is	often	used	for	missing
data	in Python	code.

NaT	(Not	a	Time)	is	used	in	pandas	to	represent	missing	values	for
date time	data	types.

A	new	missing	data	type	NA	was	introduced	with	Pandas	1.0,	which	is	an integer	type	missing	value	representation.

There	are	two	missing	values	in	this	dataset:

The	return	for	the	fourth	quarter	of	2015	is	explicitly	missing	because

the	cell	where	its	value	should	be	instead	contains	NaN.

The	return	for	the	first	quarter	of	2016	is	implicitly	missing	because
	it
simply	does	not	appear	in	the	dataset.

An	explicit	missing	value	is	a	clear	indication	of	a	missing	value.

An	implicit	missing	value	is	the	absence	of	data	that	is	not
necessarily

clearly	indicated.

The	way	that	a	dataset	is	represented	can	make	implicit	values
	explicit.	For

example,	we	can	make	the	implicit	missing	value	explicit	by	putting
years

in	the	columns.	That	scenario	would	show	the	following	[2016,	,]	in	our

data

# Handling	Missing	Values

Depending	on	the	question	we	are	trying	to	answer	or	the	task	at
hand,	one

can	choose	one	of	the	following:

Drop	missing	values

Replace	missing	values

We	can	drop	a	row	or	column	with	missing	values	using	the	dropna()

function

.	We	will	mainly	focus	on	two	parameters	of	the	dropna()	function,

the	axis	and	the	how.

dropna(axis,how):

The	axis	parameter	is	used	to	determine	if	rows	or	columns	are
removed:

0	drops	rows	that	contain	the	missing	value

1	drops	columns	that	contain	the	missing	value

The	how	parameter	is	used	to	set	the	condition	to	drop.

how='any':	drop	if	there	are	any	missing	values

how='all':	drop	if	all	values	are	missing

In [ ]:
# Use	the	code	below	to	try	the	different	arguments	of	the	dropna()	and	what
# they	return.
mir	=[['1',1,pd.NaT],['2',2,0.59],['3',pd.NaT,0.35],
[pd.NaT,pd.NaT,pd.NaT]]
df3	=	pd.DataFrame(mir,columns=['string','int','float'])
print	(df3)
print(df3.dropna(axis=0,how='any'))

  string  int float
0      1    1   NaT
1      2    2  0.59
2      3  NaT  0.35
3    NaT  NaT   NaT
  string int float
1      2   2  0.59

In [ ]:
# replace()	function
stocks	=[[2015,1,'???'],[2015,2,0.59],[2015,'???',0.35],
[2015,4,None]		,[2016,2,0.92],[2016,3,0.17],[2016,4,2.66]]
df2	=	pd.DataFrame(stocks,columns=['year','qtr','return'])
print	("Before	replacing:")
print	(df2)

Before	replacing:
   year  qtr return
0  2015    1    ???
1  2015    2   0.59
2  2015  ???   0.35
3  2015    4   None
4  2016    2   0.92
5  2016    3   0.17
6  2016    4   2.66

In [ ]:
df2.replace('???'	,	None,inplace=True)
print	("After	replacing:")
print	(df2)
print	(type(df2["return"][0]))
print	(type(df2["return"][3]))

After	replacing:
   year   qtr return
0  2015     1   None
1  2015     2   0.59
2  2015  None   0.35
3  2015     4   None
4  2016     2   0.92
5  2016     3   0.17
6  2016     4   2.66
<class 'NoneType'>
<class 'NoneType'>

In [ ]:
df2.replace((['???',None]),	pd.NA	,	inplace=True)
print	("After	replacing:")
print	(df2)

After	replacing:
   year   qtr return
0  2015     1   <NA>
1  2015     2   0.59
2  2015  <NA>   0.35
3  2015     4   <NA>
4  2016     2   0.92
5  2016     3   0.17
6  2016     4   2.66

In [ ]:
# Handling	Missing	Values:	Advanced Techniques

In [ ]:
# Filling	Missing	Values	with	Imputation
# Imputation	is	a	technique	used	to	fill	in	missing	values	with	substituted
# values.	The	simplest	form	of	imputation	is	to	replace	missing	values	with
# the	mean,	median,	or	mode	of	the	column.

In [ ]:
	# Fill	missing	values	with	the	mean
stocks	=[[2015,1,'???'],[2015,2,0.59],[2015,'???',0.35],
[2015,4,None]		,[2016,2,0.92],[2016,3,0.17],[2016,4,2.66]]
df	=	pd.DataFrame(stocks,columns=['year','qtr','return'])
df

   year  qtr return
0  2015    1    ???
1  2015    2   0.59
2  2015  ???   0.35
3  2015    4   None
4  2016    2   0.92
5  2016    3   0.17
6  2016    4   2.66

In [ ]:
# Step 2: Replace '???' with NaN
import pandas as pd
import numpy as np
df.replace('???', np.nan, inplace=True)
print(df)

   year  qtr  return
0  2015  1.0     NaN
1  2015  2.0    0.59
2  2015  NaN    0.35
3  2015  4.0     NaN
4  2016  2.0    0.92
5  2016  3.0    0.17
6  2016  4.0    2.66

/tmp/ipykernel_5775/1274682536.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('???', np.nan, inplace=True)

In [ ]:
# Step 3: Convert columns to numeric
df['year'] = pd.to_numeric(df['year'])
df['qtr'] = pd.to_numeric(df['qtr'])
df['return'] = pd.to_numeric(df['return'])
# This ensures the column can calculate mean
# NaN values will be ignored when calculating the mean

In [ ]:
# Step 4: Fill missing values with mean
df['year'].fillna(df['year'].mean(), inplace=True)
df['qtr'].fillna(df['qtr'].mean(), inplace=True)
df['return'].fillna(df['return'].mean(), inplace=True)

print(df)

   year       qtr  return
0  2015  1.000000   0.938
1  2015  2.000000   0.590
2  2015  2.666667   0.350
3  2015  4.000000   0.938
4  2016  2.000000   0.920
5  2016  3.000000   0.170
6  2016  4.000000   2.660

/tmp/ipykernel_5775/2018994473.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['year'].fillna(df['year'].mean(), inplace=True)
/tmp/ipykernel_5775/2018994473.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['qtr'].fillna(df['qtr'].mean(), inplace=True)
/tmp/ipykernel_5775/2018994473.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['return'].fillna(df['return'].mean(), inplace=True)

In [ ]:
# Step 5: Explanation
# replace('???', np.nan) → convert non-numeric placeholders to NaN
# pd.to_numeric() → ensure columns are numeric
# fillna(df['column'].mean(), inplace=True) → replace missing values with column mean

# What is forward filling (ffill)?

Forward fill means replacing missing values with the last valid
(non-missing) value that appeared above it.

It’s often used in time series or ordered data.


Think of it like this:

If a value is missing, just copy the previous value down.

In [ ]:
# Simple DataFrame
import pandas as pd
import numpy as np

data = {
    'Year': [2015, 2015, 2015, 2016, 2016, 2016],
    'Return': [0.5, np.nan, 0.7, np.nan, 1.2, np.nan]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   Year  Return
0  2015     0.5
1  2015     NaN
2  2015     0.7
3  2016     NaN
4  2016     1.2
5  2016     NaN

In [ ]:
# Step 2: Apply forward fill
df.ffill(inplace=True)
print("\nAfter forward filling:")
print(df)

After forward filling:
   Year  Return
0  2015     0.5
1  2015     0.5
2  2015     0.7
3  2016     0.7
4  2016     1.2
5  2016     1.2

In [ ]:
# Example 2: Forward fill with strings
data = {'City': ['NY', None, None, 'LA', None]}
df = pd.DataFrame(data)
df.ffill(inplace=True)
print(df)

  City
0   NY
1   NY
2   NY
3   LA
4   LA

# Backward Fill (bfill) in Python

Backward fill is a method to fill missing values (NaN) in a DataFrame or Series by using the next valid value below it.

It’s called “backward” because it looks down the column to fill missing entries.
Often used in time series or ordered data when you want missing values to take the next known value.

In [ ]:
# Example 1: Numbers
import pandas as pd
import numpy as np

df = pd.DataFrame({'Return': [0.5, np.nan, 0.7, np.nan, 1.2, np.nan]})
print("Original DataFrame:")
print(df)

df.bfill(inplace=True)
print("\nAfter backward fill:")
print(df)

# What is Interpolation?

Interpolation is a method to fill missing values (NaN) in a dataset by
estimating them based on surrounding values.

Instead of just copying the previous (ffill) or next (bfill) value,
interpolation calculates a value “in between” the known values.

Commonly used for numeric or time series data.

Types of Interpolation in Pandas

Linear (default) → estimates missing values assuming a straight line between
 known points

Time-based → estimates based on time index

Others → polynomial, spline, etc.

In [ ]:
# Example: Linear Interpolation
import pandas as pd
import numpy as np

# Sample data
df = pd.DataFrame({
    'Month': [1, 2, 3, 4, 5],
    'Sales': [100, np.nan, 150, np.nan, 200]
})

print("Original DataFrame:")
print(df)

Original DataFrame:
   Month  Sales
0      1  100.0
1      2    NaN
2      3  150.0
3      4    NaN
4      5  200.0

In [ ]:
# Interpolate missing values
df['Sales'] = df['Sales'].interpolate()

print("\nAfter interpolation:")
print(df)

After interpolation:
   Month  Sales
0      1  100.0
1      2  125.0
2      3  150.0
3      4  175.0
4      5  200.0

What is Polynomial Interpolation?

Polynomial interpolation estimates missing values using a polynomial curve that fits the known data points.
Unlike linear interpolation (a straight line), it can follow curves or trends in the data.

Useful when your data is non-linear or has a trend that isn’t straight.
In Pandas, you can use interpolate(method='polynomial', order=n) where n is the degree of the polynomial.

In [ ]:
# Example: Polynomial Interpolation (2nd degree)
import pandas as pd
import numpy as np

# Sample data
df = pd.DataFrame({
    'x': [1, 2, 3, 4, 5],
    'y': [1, np.nan, 9, np.nan, 25]
})

print("Original DataFrame:")
print(df)

Original DataFrame:
   x     y
0  1   1.0
1  2   NaN
2  3   9.0
3  4   NaN
4  5  25.0

In [ ]:
# Polynomial interpolation of order 2
df['y'] = df['y'].interpolate(method='polynomial', order=2)

print("\nAfter polynomial interpolation:")
print(df)

After polynomial interpolation:
   x     y
0  1   1.0
1  2   4.0
2  3   9.0
3  4  16.0
4  5  25.0

In [ ]:
# How it works
# Missing values are estimated using a quadratic curve (2nd-degree polynomial) that passes through the known points: (1,1), (3,9), (5,25)
# Row 1 (NaN) → 4
# Row 3 (NaN) → 16

# Notice how it follows the quadratic trend instead of a straight line.

In [ ]:
# What is dropping missing values with thresholds?

# Sometimes, a row or column has too many missing values.
# Instead of dropping every row with any missing value, you can set a threshold:

# Keep rows/columns only if they have at least N non-missing values
# Drop rows/columns that don’t meet the threshold

# Pandas uses the dropna() method with the thresh parameter:

df.dropna(thresh=N, axis=0)  # rows
df.dropna(thresh=N, axis=1)  # columns
thresh=N → minimum number of non-NaN values required to keep the row/column
axis=0 → apply on rows, axis=1 → apply on columns

In [ ]:
# Example 1: Dropping rows with threshold
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, np.nan, 3, np.nan],
    'B': [4, np.nan, np.nan, 8],
    'C': [np.nan, np.nan, 9, 10]
})

print("Original DataFrame:")
print(df)

# Drop rows that have less than 2 non-NaN values
df_cleaned = df.dropna(thresh=2, axis=0)

print("\nAfter dropping rows with less than 2 non-NaN values:")
print(df_cleaned)

# Row 1 is dropped because it only had 0 non-NaN values

Original DataFrame:
     A    B     C
0  1.0  4.0   NaN
1  NaN  NaN   NaN
2  3.0  NaN   9.0
3  NaN  8.0  10.0

After dropping rows with less than 2 non-NaN values:
     A    B     C
0  1.0  4.0   NaN
2  3.0  NaN   9.0
3  NaN  8.0  10.0

In [ ]:
# Example 2: Dropping columns with threshold
# Drop columns that have less than 3 non-NaN values
df_cleaned_cols = df.dropna(thresh=3, axis=1)

print("\nAfter dropping columns with less than 3 non-NaN values:")
print(df_cleaned_cols)
# Column A, B, and C all have less than 3 non-NaN values, so all are dropped

After dropping columns with less than 3 non-NaN values:
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

# Key Points
thresh=N → minimum number of non-missing values required
axis=0 → check rows, axis=1 → check columns
Useful when your dataset has some incomplete rows/columns but you want to keep mostly complete data

# What is Concatenation?

Concatenation is the process of combining two or more DataFrames or Series into
 a single one.


You can concatenate vertically (stack rows) or horizontally (add columns)

Use the pd.concat() function in Pandas

In [ ]:
# Syntax
# import pandas as pd
# pd.concat([df1, df2], axis=0)  # vertical (default)
# pd.concat([df1, df2], axis=1)  # horizontal

# axis=0 → stack rows (one below the other)
# axis=1 → add columns (side by side)
# ignore_index=True → re-index the resulting DataFrame

In [ ]:
# Example 1: Vertical Concatenation (stack rows)
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30]
})

df2 = pd.DataFrame({
    'Name': ['Charlie', 'David'],
    'Age': [35, 40]
})

# Vertical concatenation
df_vertical = pd.concat([df1, df2], axis=0, ignore_index=True)
print(df_vertical)
# Rows from df2 are stacked below df1

In [ ]:
# Example 2: Horizontal Concatenation (add columns)
df3 = pd.DataFrame({
    'City': ['NY', 'LA']
})

# Horizontal concatenation
df_horizontal = pd.concat([df1, df3], axis=1)
print(df_horizontal)

# Columns from df3 are added side by side with df1

In [ ]:
# 🔹 Key Points
# Use pd.concat([df1, df2]) to combine DataFrames
# axis=0 → vertical (rows), axis=1 → horizontal (columns)
# ignore_index=True → reset the index in the combined DataFrame
# Works with DataFrames or Series

# What is Join in Pandas?

A join combines two DataFrames based on a common column (key), similar to joins
 in SQL.


You use it when you have related data in different tables and want to merge
them together.

The common column(s) is called a key.

Types of Joins


inner	Keeps only rows with keys present in both DataFrames

left	Keeps all rows from the left DataFrame, adds matching from right

right	Keeps all rows from the right DataFrame, adds matching from left

outer	Keeps all rows from both DataFrames, fills missing with NaN

🔹 1. merge() in Pandas
Used to combine two DataFrames based on a key column(s).
Works like SQL joins: inner, left, right, outer.
Syntax:
pd.merge(df1, df2, on='key_column', how='inner')  
You can specify which column(s) to join on using on=
Can join on multiple columns

Example:

pd.merge(df1, df2, on='ID', how='left')

🔹 2. join() in Pandas

Used to combine DataFrames based on their index by default.
Simpler syntax if you want to join on row labels (index).
Can also join on columns if you use set_index() first.
df1.join(df2, how='left')  # joins using index of df1 and df2
join() is basically a shortcut for merge on index
Supports left, right, inner, outer

In [ ]:
# Example: Join DataFrames
import pandas as pd

# Left DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# Right DataFrame
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'City': ['LA', 'NY', 'SF']
})

# Inner join on ID
df_inner = pd.merge(df1, df2, on='ID', how='inner')
print("Inner Join:")
print(df_inner)
# Only IDs 2 and 3 appear because they exist in both DataFrames

In [ ]:
# Left Join Example
df_left = pd.merge(df1, df2, on='ID', how='left')
print("\nLeft Join:")
print(df_left)
# All rows from df1 are kept. Missing matches from df2 are NaN

In [ ]:
import pandas as pd

# Left DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# Right DataFrame
df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'City': ['LA', 'NY', 'SF']
})

df_right = pd.merge(df1, df2, on='ID', how='right')
print("Right Join:")
print(df_right)
# ID 4 is kept from df2 even though it doesn’t exist in df1 → Name is NaN

In [ ]:
# 2️ Outer Join

# Keeps all rows from both DataFrames and fills missing values with NaN.

df_outer = pd.merge(df1, df2, on='ID', how='outer')
print("Outer Join:")
print(df_outer)

In [ ]:
# Example: merge vs join
import pandas as pd

# DataFrames
df1 = pd.DataFrame({'ID':[1,2,3], 'Name':['Alice','Bob','Charlie']})
df2 = pd.DataFrame({'ID':[2,3,4], 'City':['LA','NY','SF']})

# Using merge
df_merge = pd.merge(df1, df2, on='ID', how='inner')
print("Merge result:\n", df_merge)

# Using join (set index first)
df1_indexed = df1.set_index('ID')
df2_indexed = df2.set_index('ID')
df_join = df1_indexed.join(df2_indexed, how='inner')
print("\nJoin result:\n", df_join)